services:
  web:
    restart: always
    build:
      context: ./                # 指定dockerfile文件的所在路径  
      dockerfile: Dockerfile    # 指定Dockerfile文件名称 
    image: web:t1          #自定义镜像名和版本号
    container_name: web
    ports:
      - 8080:3000
    volumes:
      - data:/data
  

volumes:
  data:
    size: 5Gi